title: Modokemdev Blog
author: Marco André Echeverria
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog to talk about my programming experience and stuff that I like!

# social links
twitter_username: https://twitter.com/andreche2/
github_username:  https://github.com/marcoandre1/

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
